name: Deploy to AWS Lambda

on:
  workflow_run:
    workflows: ["Release Pipeline"]  # Trigger when the release pipeline completes
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1  # Change to your region

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t package/
          cd package && zip -r ../function.zip .
          cd .. && zip -g function.zip lambda_function.py

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name thupsFunc \
            --zip-file fileb://function.zip
