name: Release Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build pipeline runs first

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: function-zip
          path: function.zip

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name thupsFunc \
            --zip-file fileb://function.zip \
            --region ${{ secrets.AWS_REGION }} \
            --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} \
            --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run integration tests
        run: |
          pytest integration_tests/  # Assuming integration tests are in the "integration_tests" folder
